# Generated by Django 3.0.2 on 2020-08-13 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ans',
            fields=[
                ('ans_Id', models.AutoField(primary_key=True, serialize=False)),
                ('ans_Text', models.CharField(max_length=144)),
                ('ans_User', models.CharField(max_length=6)),
                ('ans_UserType', models.CharField(max_length=1)),
                ('ans_QuesId', models.CharField(max_length=6)),
                ('ans_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 703531))),
            ],
        ),
        migrations.CreateModel(
            name='ansLike',
            fields=[
                ('ansLike_Id', models.AutoField(primary_key=True, serialize=False)),
                ('ansLike_User', models.CharField(max_length=6)),
                ('ansLike_UserType', models.CharField(max_length=1)),
                ('ansLike_AnsId', models.CharField(max_length=6)),
                ('ansLike_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 703531))),
            ],
        ),
        migrations.CreateModel(
            name='fs',
            fields=[
                ('fs_Id', models.AutoField(primary_key=True, serialize=False)),
                ('fs_Text', models.CharField(max_length=500)),
                ('fs_User', models.CharField(max_length=6)),
                ('fs_UserType', models.CharField(max_length=1)),
                ('fs_Type', models.CharField(max_length=8)),
                ('fs_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 702500))),
            ],
        ),
        migrations.CreateModel(
            name='fsComment',
            fields=[
                ('fsComment_Id', models.AutoField(primary_key=True, serialize=False)),
                ('fsComment_Text', models.CharField(default='巧了 我也是这样的', max_length=144)),
                ('fsComment_User', models.CharField(max_length=6)),
                ('fsComment_UserType', models.CharField(max_length=1)),
                ('fsComment_Srv', models.CharField(max_length=6)),
                ('fsComment_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 701510))),
            ],
        ),
        migrations.CreateModel(
            name='fsLike',
            fields=[
                ('fsLike_Id', models.AutoField(primary_key=True, serialize=False)),
                ('fsLike_User', models.CharField(max_length=6)),
                ('fsLike_UserType', models.CharField(max_length=1)),
                ('fsLike_AnsId', models.CharField(max_length=6)),
                ('fsLike_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 702500))),
            ],
        ),
        migrations.CreateModel(
            name='ques',
            fields=[
                ('ques_Id', models.AutoField(primary_key=True, serialize=False)),
                ('ques_Text', models.CharField(max_length=144)),
                ('ques_User', models.CharField(max_length=6)),
                ('ques_UserType', models.CharField(max_length=1)),
                ('ques_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 702500))),
            ],
        ),
        migrations.CreateModel(
            name='quesLike',
            fields=[
                ('quesLike_Id', models.AutoField(primary_key=True, serialize=False)),
                ('quesLike_User', models.CharField(max_length=6)),
                ('quesLike_UserType', models.CharField(max_length=1)),
                ('quesLike_AnsId', models.CharField(max_length=6)),
                ('quesLike_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 702500))),
            ],
        ),
        migrations.CreateModel(
            name='srvA',
            fields=[
                ('srvA_Id', models.AutoField(primary_key=True, serialize=False)),
                ('srvA_Preface', models.FilePathField(blank=True, null=True, path='smile/preface/')),
                ('srvA_Info', models.CharField(blank=True, max_length=400, null=True)),
                ('srvA_Usernum', models.IntegerField(default=0)),
                ('srvA_Collectnum', models.IntegerField(default=0)),
                ('srvA_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 705531))),
                ('srvA_Type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='srvC',
            fields=[
                ('srvC_Id', models.AutoField(primary_key=True, serialize=False)),
                ('srvC_Preface', models.FilePathField(blank=True, null=True, path='smile/preface/')),
                ('srvC_Info', models.CharField(blank=True, max_length=400, null=True)),
                ('srvC_Usernum', models.IntegerField(default=0)),
                ('srvC_Collectnum', models.IntegerField(default=0)),
                ('srvC_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 706524))),
                ('srvC_Type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='srvCommentA',
            fields=[
                ('srvCommentA_Id', models.AutoField(primary_key=True, serialize=False)),
                ('srvCommentA_Text', models.CharField(default='还可以', max_length=144)),
                ('srvCommentA_Star', models.CharField(max_length=1)),
                ('srvCommentA_User', models.CharField(max_length=6)),
                ('srvCommentA_UserType', models.CharField(max_length=1)),
                ('srvCommentA_Srv', models.CharField(max_length=6)),
                ('srvCommentA_SrvType', models.CharField(max_length=1)),
                ('srvCommentA_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 705531))),
            ],
        ),
        migrations.CreateModel(
            name='srvCommentC',
            fields=[
                ('srvCommentC_Id', models.AutoField(primary_key=True, serialize=False)),
                ('srvCommentC_Text', models.CharField(default='还可以', max_length=144)),
                ('srvCommentC_Star', models.CharField(max_length=1)),
                ('srvCommentC_User', models.CharField(max_length=6)),
                ('srvCommentC_UserType', models.CharField(max_length=1)),
                ('srvCommentC_Srv', models.CharField(max_length=6)),
                ('srvCommentC_SrvType', models.CharField(max_length=1)),
                ('srvCommentC_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 707521))),
            ],
        ),
        migrations.CreateModel(
            name='srvCommentS',
            fields=[
                ('srvCommentS_Id', models.AutoField(primary_key=True, serialize=False)),
                ('srvCommentS_Text', models.CharField(default='还可以', max_length=144)),
                ('srvCommentS_Star', models.CharField(max_length=1)),
                ('srvCommentS_User', models.CharField(max_length=6)),
                ('srvCommentS_UserType', models.CharField(max_length=1)),
                ('srvCommentS_Srv', models.CharField(max_length=6)),
                ('srvCommentS_SrvType', models.CharField(max_length=1)),
                ('srvCommentS_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 704494))),
            ],
        ),
        migrations.CreateModel(
            name='srvLikeA',
            fields=[
                ('srvLikeA_Id', models.AutoField(primary_key=True, serialize=False)),
                ('srvLikeA_User', models.CharField(max_length=6)),
                ('srvLikeA_UserType', models.CharField(max_length=1)),
                ('srvLikeA_AnsId', models.CharField(max_length=6)),
                ('srvLikeA_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 706524))),
            ],
        ),
        migrations.CreateModel(
            name='srvLikeC',
            fields=[
                ('srvLikeC_Id', models.AutoField(primary_key=True, serialize=False)),
                ('srvLikeC_User', models.CharField(max_length=6)),
                ('srvLikeC_UserType', models.CharField(max_length=1)),
                ('srvLikeC_CnsId', models.CharField(max_length=6)),
                ('srvLikeC_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 714528))),
            ],
        ),
        migrations.CreateModel(
            name='srvLikeS',
            fields=[
                ('srvLikeS_Id', models.AutoField(primary_key=True, serialize=False)),
                ('srvLikeS_User', models.CharField(max_length=6)),
                ('srvLikeS_UserType', models.CharField(max_length=1)),
                ('srvLikeS_AnsId', models.CharField(max_length=6)),
                ('srvLikeS_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 704494))),
            ],
        ),
        migrations.CreateModel(
            name='srvS',
            fields=[
                ('srvS_Id', models.AutoField(primary_key=True, serialize=False)),
                ('srvS_Preface', models.FilePathField(blank=True, null=True, path='smile/preface/')),
                ('srvS_Info', models.CharField(blank=True, max_length=400, null=True)),
                ('srvS_Usernum', models.IntegerField(default=0)),
                ('srvS_Collectnum', models.IntegerField(default=0)),
                ('srvS_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 703531))),
                ('srvS_Type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='srvUserA',
            fields=[
                ('srvUserA_RecordId', models.AutoField(primary_key=True, serialize=False)),
                ('srvUserA_Id', models.CharField(max_length=6)),
                ('srvUserA_Type', models.CharField(max_length=1)),
                ('srvUserA_SrvId', models.CharField(max_length=6)),
                ('srvUserA_SrvType', models.CharField(max_length=1)),
                ('srvUserA_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 706524))),
            ],
        ),
        migrations.CreateModel(
            name='srvUserC',
            fields=[
                ('srvUserC_RecordId', models.AutoField(primary_key=True, serialize=False)),
                ('srvUserC_Id', models.CharField(max_length=6)),
                ('srvUserC_Type', models.CharField(max_length=1)),
                ('srvUserC_SrvId', models.CharField(max_length=6)),
                ('srvUserC_SrvType', models.CharField(max_length=1)),
                ('srvUserC_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 715524))),
            ],
        ),
        migrations.CreateModel(
            name='srvUserS',
            fields=[
                ('srvUserS_RecordId', models.AutoField(primary_key=True, serialize=False)),
                ('srvUserS_Id', models.CharField(max_length=6)),
                ('srvUserS_Type', models.CharField(max_length=1)),
                ('srvUserS_SrvId', models.CharField(max_length=6)),
                ('srvUserS_SrvType', models.CharField(max_length=1)),
                ('srvUserS_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 705531))),
            ],
        ),
        migrations.CreateModel(
            name='userA',
            fields=[
                ('userA_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userA_Alias', models.CharField(max_length=20, unique=True)),
                ('userA_Pwd', models.CharField(default='66666666', max_length=20)),
                ('userA_Phone', models.CharField(default='13713800000', max_length=12, unique=True)),
                ('userA_Email', models.EmailField(max_length=254, unique=True)),
                ('userA_Gender', models.BooleanField(default=True)),
                ('userA_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 716521))),
                ('userA_Type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='userB',
            fields=[
                ('userB_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userB_Blias', models.CharField(max_length=20, unique=True)),
                ('userB_Pwd', models.CharField(default='66666666', max_length=20)),
                ('userB_Phone', models.CharField(default='13713800000', max_length=12, unique=True)),
                ('userB_Email', models.EmailField(max_length=254, unique=True)),
                ('userB_Gender', models.BooleanField(default=True)),
                ('userB_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 717520))),
                ('userB_Type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='userC',
            fields=[
                ('userC_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userC_Clias', models.CharField(max_length=20, unique=True)),
                ('userC_Pwd', models.CharField(default='66666666', max_length=20)),
                ('userC_Phone', models.CharField(default='13713800000', max_length=12, unique=True)),
                ('userC_Email', models.EmailField(max_length=254, unique=True)),
                ('userC_Gender', models.BooleanField(default=True)),
                ('userC_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 718516))),
                ('userC_Type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='userCommentA',
            fields=[
                ('userCommentA_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userCommentA_text', models.CharField(default='还行', max_length=144)),
                ('userCommentA_star', models.CharField(default='A', max_length=1)),
                ('userCommentA_ERId', models.CharField(max_length=6)),
                ('userCommentA_ERType', models.CharField(max_length=1)),
                ('userCommentA_EEId', models.CharField(max_length=6)),
                ('userCommentA_EEType', models.CharField(max_length=1)),
                ('userCommentA_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 717520))),
            ],
        ),
        migrations.CreateModel(
            name='userCommentB',
            fields=[
                ('userCommentB_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userCommentB_text', models.CharField(default='还行', max_length=144)),
                ('userCommentB_star', models.CharField(default='B', max_length=1)),
                ('userCommentB_ERId', models.CharField(max_length=6)),
                ('userCommentB_ERType', models.CharField(max_length=1)),
                ('userCommentB_EEId', models.CharField(max_length=6)),
                ('userCommentB_EEType', models.CharField(max_length=1)),
                ('userCommentB_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 718516))),
            ],
        ),
        migrations.CreateModel(
            name='userCommentC',
            fields=[
                ('userCommentC_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userCommentC_Text', models.CharField(default='还行', max_length=144)),
                ('userCommentC_Star', models.CharField(default='C', max_length=1)),
                ('userCommentC_ERId', models.CharField(max_length=6)),
                ('userCommentC_ERType', models.CharField(max_length=1)),
                ('userCommentC_EEId', models.CharField(max_length=6)),
                ('userCommentC_EEType', models.CharField(max_length=1)),
                ('userCommentC_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 719456))),
            ],
        ),
        migrations.CreateModel(
            name='userCommentS',
            fields=[
                ('userCommentS_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userCommentS_Text', models.CharField(default='还行', max_length=144)),
                ('userCommentS_Star', models.CharField(default='A', max_length=1)),
                ('userCommentS_ERId', models.CharField(max_length=6)),
                ('userCommentS_ERType', models.CharField(max_length=1)),
                ('userCommentS_EEId', models.CharField(max_length=6)),
                ('userCommentS_EEType', models.CharField(max_length=1)),
                ('userCommentS_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 716521))),
            ],
        ),
        migrations.CreateModel(
            name='userD',
            fields=[
                ('userD_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userD_Alias', models.CharField(max_length=20, unique=True)),
                ('userD_Pwd', models.CharField(default='66666666', max_length=20)),
                ('userD_Phone', models.CharField(default='13713800000', max_length=12, unique=True)),
                ('userD_Email', models.EmailField(max_length=254, unique=True)),
                ('userD_Gender', models.BooleanField(default=True)),
                ('userD_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 719456))),
            ],
        ),
        migrations.CreateModel(
            name='userE',
            fields=[
                ('userE_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userE_Alias', models.CharField(max_length=20, unique=True)),
                ('userE_Pwd', models.CharField(default='66666666', max_length=20)),
                ('userE_Phone', models.CharField(default='13713800000', max_length=12, unique=True)),
                ('userE_Email', models.EmailField(max_length=254, unique=True)),
                ('userE_Gender', models.BooleanField(default=True)),
                ('userE_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 719456))),
            ],
        ),
        migrations.CreateModel(
            name='userLikeA',
            fields=[
                ('userLikeA_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userLikeA_User', models.CharField(max_length=6)),
                ('userLikeA_UserId', models.CharField(max_length=6)),
                ('userLikeA_UserType', models.CharField(max_length=1)),
                ('userLikeA_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 716521))),
            ],
        ),
        migrations.CreateModel(
            name='userLikeB',
            fields=[
                ('userLikeB_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userLikeB_User', models.CharField(max_length=6)),
                ('userLikeB_UserId', models.CharField(max_length=6)),
                ('userLikeB_UserType', models.CharField(max_length=1)),
                ('userLikeB_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 717520))),
            ],
        ),
        migrations.CreateModel(
            name='userLikeC',
            fields=[
                ('userLikeC_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userLikeC_User', models.CharField(max_length=6)),
                ('userLikeC_UserId', models.CharField(max_length=6)),
                ('userLikeC_UserType', models.CharField(max_length=1)),
                ('userLikeC_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 718516))),
            ],
        ),
        migrations.CreateModel(
            name='userLikeS',
            fields=[
                ('userLikeS_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userLikeS_User', models.CharField(max_length=6)),
                ('userLikeS_UserId', models.CharField(max_length=6)),
                ('userLikeS_UserType', models.CharField(max_length=1)),
                ('userLikeS_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 715524))),
            ],
        ),
        migrations.CreateModel(
            name='userR',
            fields=[
                ('userR_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userR_Alias', models.CharField(max_length=20, unique=True)),
                ('userR_Pwd', models.CharField(default='66666666', max_length=20)),
                ('userR_Phone', models.CharField(default='13713800000', max_length=12, unique=True)),
                ('userR_Email', models.EmailField(max_length=254, unique=True)),
                ('userR_Gender', models.BooleanField(default=True)),
                ('userR_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 715524))),
                ('userR_Type', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='userS',
            fields=[
                ('userS_Id', models.AutoField(primary_key=True, serialize=False)),
                ('userS_Alias', models.CharField(max_length=20, unique=True)),
                ('userS_Pwd', models.CharField(default='66666666', max_length=20)),
                ('userS_Phone', models.CharField(default='13713800000', max_length=12, unique=True)),
                ('userS_Email', models.EmailField(max_length=254, unique=True)),
                ('userS_Gender', models.BooleanField(default=True)),
                ('userS_Time', models.DateTimeField(default=datetime.datetime(2020, 8, 13, 13, 24, 9, 715524))),
                ('userS_Type', models.CharField(max_length=8)),
            ],
        ),
    ]
